---
url: "https://petstore.swagger.io/v2/swagger.json"
dom_id: "#swagger-ui"
validatorUrl: "https://validator.swagger.io/validator"
oauth2RedirectUrl: "https://cloud.mediusflow.com/documentation/api/documentation/o2c.html"
