# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Swagger UI (dist) to Azure Web App - mf11swagger02-master

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy dist/ to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: mf11swagger02-master
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C8D52165E3C54AC7AE99DE0A23016250 }}
          package: dist